// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    AI: any,
    MY_BUCKET: any,
    API_KEY: any,
    R2_DOMAIN: any,
    TEXT_MODEL_PREFIX: string,
    IMAGE_MODEL_PREFIX: string,
    EMBEDDING_MODEL_PREFIX: string;
}