#:schema node_modules/wrangler/config-schema.json
name = "white-scene-699e"
main = "src/index.ts"
compatibility_date = "2024-04-05"
workers_dev = true

[vars]
API_KEY = "cf-BHysWVezUVCiRRv596rcQtrJNohu3Zi5"
MODEL_PREFIX = "gpt-3.5-"

[ai]
binding = "AI"
